name: 'wrike_demo'
version: 0.0.1
description: Demo app
author: Victor Sheyanov

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  polymer: ^1.0.0-rc.2
  browser: ^0.10.0
  web_components: ^0.12.0
  reflectable: ^0.3.1

transformers:
- web_components:
    entry_points:
    - web/index.html
- reflectable:
    entry_points:
    - web/index.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives

environment:
  sdk: ">=1.8.0 <2.0.0"